version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15-browsers

    working_directory: ~/realworld-starter-kit

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn test
      - run:
          name: Lints
          command: |
            yarn lint:eslint-check
            yarn lint:hbs
            yarn lint:js
      
      - store_test_results:
          path: test-results
